import 'package:flutter/material.dart';
class MasterColorSchemePreset {
  const MasterColorSchemePreset._();

  static TextTheme defaultLightTextTheme = TextTheme(
    displayLarge: TextStyle(color:defaultLightScheme.onPrimary),
    displayMedium: TextStyle(color:defaultLightScheme.onPrimary),
    displaySmall: TextStyle(color:defaultLightScheme.onPrimary),
    headlineLarge: TextStyle(color:defaultLightScheme.onPrimary),
    headlineMedium: TextStyle(color:defaultLightScheme.onPrimary),
    headlineSmall: TextStyle(color:defaultLightScheme.onPrimary),
    titleLarge: TextStyle(color:defaultLightScheme.onPrimary),
    titleMedium: TextStyle(color:defaultLightScheme.onPrimary),
    titleSmall: TextStyle(color:defaultLightScheme.onPrimary),
    bodyLarge: TextStyle(color:defaultLightScheme.onPrimary),
    bodyMedium: TextStyle(color:defaultLightScheme.onPrimary),
    bodySmall: TextStyle(color:defaultLightScheme.onPrimary),
    labelLarge: TextStyle(color:defaultLightScheme.onPrimary),
    labelMedium: TextStyle(color:defaultLightScheme.onPrimary),
    labelSmall: TextStyle(color:defaultLightScheme.onPrimary),
  );

  static const ColorScheme defaultLightScheme = ColorScheme(
    brightness: Brightness.light,
    primary: Color(0xFFFFF5D2),
    onPrimary: Color(0xFF333333),
    secondary: Color(0xFFF75C2F),
    onSecondary: Color(0xFFFFF5D2),
    error: Color(0xFFEF5253),
    onError: Color(0xFFFAFAFA),
    background: Color(0xFFFFFEFC),
    onBackground: Color(0xFF333333),
    surface: Color(0xFFFFFEFC),
    onSurface: Color(0xFF333333),
    primaryContainer: Color(0xFFFFC700),
    onPrimaryContainer: Color(0xFFFFF5D2),
    secondaryContainer: Color(0xFFF75C2F),
    onSecondaryContainer: Color(0xFFFAFAFA),
    tertiary: Color(0xFF5D5D5D),
    onTertiary: Color(0xFFFAFAFA),
    tertiaryContainer: Color(0xFFFF00FF),
    onTertiaryContainer: Color(0xFF00FF00),
    errorContainer: Color(0xFFCC00CC),
    onErrorContainer: Color(0xFFCCFFCC),
    surfaceVariant: Color(0xFFFFFF00),
    onSurfaceVariant: Color(0xFF0000FF),
    outline: Color(0xFFCCCC00),
    shadow: Color(0xFFFF0000),
    inverseSurface: Color(0xFF00F0FF),
    onInverseSurface: Color(0xFF990000),
    inversePrimary: Color(0xFFAA99DD),
    surfaceTint: Color(0xFFAADD22),
  );

  static TextTheme defaultDarkTextTheme = TextTheme(
    displayLarge: TextStyle(color:defaultDarkScheme.onPrimary),
    displayMedium: TextStyle(color:defaultDarkScheme.onPrimary),
    displaySmall: TextStyle(color:defaultDarkScheme.onPrimary),
    headlineLarge: TextStyle(color:defaultDarkScheme.onPrimary),
    headlineMedium: TextStyle(color:defaultDarkScheme.onPrimary),
    headlineSmall: TextStyle(color:defaultDarkScheme.onPrimary),
    titleLarge: TextStyle(color:defaultDarkScheme.onPrimary),
    titleMedium: TextStyle(color:defaultDarkScheme.onPrimary),
    titleSmall: TextStyle(color:defaultDarkScheme.onPrimary),
    bodyLarge: TextStyle(color:defaultDarkScheme.onPrimary),
    bodyMedium: TextStyle(color:defaultDarkScheme.onPrimary),
    bodySmall: TextStyle(color:defaultDarkScheme.onPrimary),
    labelLarge: TextStyle(color:defaultDarkScheme.onPrimary),
    labelMedium: TextStyle(color:defaultDarkScheme.onPrimary),
    labelSmall: TextStyle(color:defaultDarkScheme.onPrimary),
  );

  static const ColorScheme defaultDarkScheme = ColorScheme(
    brightness: Brightness.dark,
    primary: Color(0xFF354F6F),
    onPrimary: Color(0xFFFAFAFA),
    secondary: Color(0xFFF75C2F),
    onSecondary: Color(0xFFFAFAFA),
    error: Color(0xFFEF5253),
    onError: Color(0xFFFAFAFA),
    background: Color(0xFF041529),
    onBackground: Color(0xFFFAFAFA),
    surface: Color(0xFF041529),
    onSurface: Color(0xFFFAFAFA),
    primaryContainer: Color(0xFFF75C2F),
    onPrimaryContainer: Color(0xFFFAFAFA),
    secondaryContainer: Color(0xFF041529),
    onSecondaryContainer: Color(0xFFFAFAFA),
    tertiary: Color(0xFFA2A2A2),
    onTertiary: Color(0xFF333333),
    tertiaryContainer: Color(0xFFFF00FF),
    onTertiaryContainer: Color(0xFF00FF00),
    errorContainer: Color(0xFFCC00CC),
    onErrorContainer: Color(0xFFCCFFCC),
    surfaceVariant: Color(0xFFFFFF00),
    onSurfaceVariant: Color(0xFF0000FF),
    outline: Color(0xFFCCCC00),
    shadow: Color(0xFFFF0000),
    inverseSurface: Color(0xFF00F0FF),
    onInverseSurface: Color(0xFF990000),
    inversePrimary: Color(0xFFAA99DD),
    surfaceTint: Color(0xFFAADD22),
  );

  static List<Map<String, dynamic>> getColorSets() {
    List<Map<String, dynamic>> themes = [
      {'name': 'theme1', 'theme': MasterColorSchemePreset.theme1},
      {'name': 'theme2', 'theme': MasterColorSchemePreset.theme2},
      {'name': 'theme3', 'theme': MasterColorSchemePreset.theme3},
      {'name': 'theme4', 'theme': MasterColorSchemePreset.theme4},
      {'name': 'theme5', 'theme': MasterColorSchemePreset.theme5},
      {'name': 'theme6', 'theme': MasterColorSchemePreset.theme6},
      {'name': 'theme7', 'theme': MasterColorSchemePreset.theme7},
      {'name': 'theme8', 'theme': MasterColorSchemePreset.theme8},
      {'name': 'theme9', 'theme': MasterColorSchemePreset.theme9},
      {'name': 'theme10', 'theme': MasterColorSchemePreset.theme10},
      {'name': 'theme11', 'theme': MasterColorSchemePreset.theme11},
    ];

    return List.generate(
      themes.length,
      (int index) {
        return {
          'colorId': themes[index]['name'],
          'rules': MasterColorSchemePreset.colors[themes[index]['name']],
          ...themes[index]['theme']
        };
      }
    );
  }

  static final Map<String, List<String>> colors = {
    'theme1': [
      '0xFFF75C2F',
      '0xFFFFC700',
      '0xFFFFF5D2',
      '0xFFFFFEFC',
    ],
    'theme2': [
      '0xFF0D5661',
      '0xFFFFB11B',
      '0xFFFFCF71',
      '0xFFFFF7E8',
      '0xFFFFFEFC',
    ],
    'theme3': [
      '0xFFF18D5F',
      '0xFFFDF0EA',
      '0xFF464EF2',
      '0xFFF9F9F9',
    ],
    'theme4': [
      '0xFF255F85',
      '0xFFE98A15',
      '0xFFFFFFEA',
      '0xFFF9F9F9',
    ],
    'theme5': [
      '0xFFF4AF1B',
      '0xFFFFD55A',
      '0xFF66D47E',
      '0xFFFEFEFE',
    ],
    'theme6': [
      '0xFF197BBD',
      '0xFFF05D4D',
      '0xFF88AB75',
      '0xFFFEFEFE',
    ],
    'theme7': [
      '0xFFEF5253',
      '0xFFF4D474',
      '0xFFFAF3E3',
      '0xFFFEFEFE',
    ],
    'theme8': [
      '0xFF143D59',
      '0xFFF4B41A',
      '0xFFFFDD8C',
      '0xFFFEFEFE',
    ],
    'theme9': [
      '0xFFFFBC57',
      '0xFFFFDD8C',
      '0xFFDD7373',
      '0xFFFEFEFE',
    ],
    'theme10': [
      '0xFF53A644',
      '0xFFFFBC59',
      '0xFFFFFEE6',
      '0xFFFEFEFE',
    ],
    'theme11': [
      '0xFF041529',
      '0xFF354F6F',
      '0xFFF75C2F',
      '0xFFFAFAFA',
    ]
  };

  static final Map<String, String> theme1 = {
    'schemeName': 'theme1',
    'brightness': 'light',
    'primary': '0xFFFFF5D2',
    'onPrimary': '0xFF333333',
    'secondary': '0xFFF75C2F',
    'onSecondary': '0xFFFFF5D2',
    'error': '0xFFEF5253',
    'onError': '0xFFFAFAFA',
    'background': '0xFFFFFEFC',
    'onBackground': '0xFF333333',
    'surface': '0xFFFFFEFC',
    'onSurface': '0xFF333333',
    'primaryContainer': '0xFFFFC700',
    'onPrimaryContainer': '0xFFFFF5D2',
    'secondaryContainer': '0xFFF75C2F',
    'onSecondaryContainer': '0xFFFAFAFA',
    'tertiary': '0xFF5D5D5D',
    'onTertiary': '0xFFFAFAFA',
    'tertiaryContainer': '0xFFFF00FF',
    'onTertiaryContainer': '0xFF00FF00',
    'errorContainer': '0xFFCC00CC',
    'onErrorContainer': '0xFFCCFFCC',
    'surfaceVariant': '0xFFFFFF00',
    'onSurfaceVariant': '0xFF0000FF',
    'outline': '0xFFCCCC00',
    'shadow': '0xFFFF0000',
    'inverseSurface': '0xFF00F0FF',
    'onInverseSurface': '0xFF990000',
    'inversePrimary': '0xFFAA99DD',
    'surfaceTint': '0xFFAADD22',
  };

  static final Map<String, String> theme2 = {
    'schemeName': 'theme2',
    'brightness': 'light',
    'primary': '0xFFFFF7E8',
    'onPrimary': '0xFF333333',
    'secondary': '0xFFFFB11B',
    'onSecondary': '0xFFFFF7E8',
    'error': '0xFFEF5253',
    'onError': '0xFFFAFAFA',
    'background': '0xFFFFFEFC',
    'onBackground': '0xFF333333',
    'surface': '0xFFFFF7E8',
    'onSurface': '0xFF333333',
    'primaryContainer': '0xFFFFB11B',
    'onPrimaryContainer': '0xFFFFF7E8',
    'secondaryContainer': '0xFF0D5661',
    'onSecondaryContainer': '0xFFFAFAFA',
    'tertiary': '0xFF5D5D5D',
    'onTertiary': '0xFFFAFAFA',
    'tertiaryContainer': '0xFFFF00FF',
    'onTertiaryContainer': '0xFF00FF00',
    'errorContainer': '0xFFCC00CC',
    'onErrorContainer': '0xFFCCFFCC',
    'surfaceVariant': '0xFFFFFF00',
    'onSurfaceVariant': '0xFF0000FF',
    'outline': '0xFFCCCC00',
    'shadow': '0xFFFF0000',
    'inverseSurface': '0xFF00F0FF',
    'onInverseSurface': '0xFF990000',
    'inversePrimary': '0xFFAA99DD',
    'surfaceTint': '0xFFAADD22',
  };

  static final Map<String, String> theme3 = {
    'schemeName': 'theme3',
    'brightness': 'light',
    'primary': '0xFFFDF0EA',
    'onPrimary': '0xFF333333',
    'secondary': '0xFF464EF2',
    'onSecondary': '0xFFFDF0EA',
    'error': '0xFFEF5253',
    'onError': '0xFFFAFAFA',
    'background': '0xFFF9F9F9',
    'onBackground': '0xFF333333',
    'surface': '0xFFFDF0EA',
    'onSurface': '0xFF333333',
    'primaryContainer': '0xFFF18D5F',
    'onPrimaryContainer': '0xFFFDF0EA',
    'secondaryContainer': '0xFFF18D5F',
    'onSecondaryContainer': '0xFFFAFAFA',
    'tertiary': '0xFF5D5D5D',
    'onTertiary': '0xFFFAFAFA',
    'tertiaryContainer': '0xFFFF00FF',
    'onTertiaryContainer': '0xFF00FF00',
    'errorContainer': '0xFFCC00CC',
    'onErrorContainer': '0xFFCCFFCC',
    'surfaceVariant': '0xFFFFFF00',
    'onSurfaceVariant': '0xFF0000FF',
    'outline': '0xFFCCCC00',
    'shadow': '0xFFFF0000',
    'inverseSurface': '0xFF00F0FF',
    'onInverseSurface': '0xFF990000',
    'inversePrimary': '0xFFAA99DD',
    'surfaceTint': '0xFFAADD22',
  };

  static final Map<String, String> theme4 = {
    'schemeName': 'theme4',
    'brightness': 'light',
    'primary': '0xFFFFFFEA',
    'onPrimary': '0xFF333333',
    'secondary': '0xFFE98A15',
    'onSecondary': '0xFFFFFFEA',
    'error': '0xFFEF5253',
    'onError': '0xFFFAFAFA',
    'background': '0xFFF9F9F9',
    'onBackground': '0xFF333333',
    'surface': '0xFFFFFFEA',
    'onSurface': '0xFF333333',
    'primaryContainer': '0xFFE98A15',
    'onPrimaryContainer': '0xFFFFFFEA',
    'secondaryContainer': '0xFF255F85',
    'onSecondaryContainer': '0xFFFAFAFA',
    'tertiary': '0xFF5D5D5D',
    'onTertiary': '0xFFFAFAFA',
    'tertiaryContainer': '0xFFFF00FF',
    'onTertiaryContainer': '0xFF00FF00',
    'errorContainer': '0xFFCC00CC',
    'onErrorContainer': '0xFFCCFFCC',
    'surfaceVariant': '0xFFFFFF00',
    'onSurfaceVariant': '0xFF0000FF',
    'outline': '0xFFCCCC00',
    'shadow': '0xFFFF0000',
    'inverseSurface': '0xFF00F0FF',
    'onInverseSurface': '0xFF990000',
    'inversePrimary': '0xFFAA99DD',
    'surfaceTint': '0xFFAADD22',
  };

  static final Map<String, String> theme5 = {
    'schemeName': 'theme5',
    'brightness': 'light',
    'primary': '0xFFFFD55A',
    'onPrimary': '0xFF333333',
    'secondary': '0xFF66D47E',
    'onSecondary': '0xFFFAFAFA',
    'error': '0xFFEF5253',
    'onError': '0xFFFAFAFA',
    'background': '0xFFFEFEFE',
    'onBackground': '0xFF333333',
    'surface': '0xFFFEFEFE',
    'onSurface': '0xFF333333',
    'primaryContainer': '0xFFFEFEFE',
    'onPrimaryContainer': '0xFFF4AF1B',
    'secondaryContainer': '0xFFFEFEFE',
    'onSecondaryContainer': '0xFF333333',
    'tertiary': '0xFF5D5D5D',
    'onTertiary': '0xFFFAFAFA',
    'tertiaryContainer': '0xFFFF00FF',
    'onTertiaryContainer': '0xFF00FF00',
    'errorContainer': '0xFFCC00CC',
    'onErrorContainer': '0xFFCCFFCC',
    'surfaceVariant': '0xFFFFFF00',
    'onSurfaceVariant': '0xFF0000FF',
    'outline': '0xFFCCCC00',
    'shadow': '0xFFFF0000',
    'inverseSurface': '0xFF00F0FF',
    'onInverseSurface': '0xFF990000',
    'inversePrimary': '0xFFAA99DD',
    'surfaceTint': '0xFFAADD22',
  };

  static final Map<String, String> theme6 = {
    'schemeName': 'theme6',
    'brightness': 'light',
    'primary': '0xFF88AB75',
    'onPrimary': '0xFF333333',
    'secondary': '0xFF197BBD',
    'onSecondary': '0xFFFAFAFA',
    'error': '0xFFEF5253',
    'onError': '0xFFFAFAFA',
    'background': '0xFFFEFEFE',
    'onBackground': '0xFF333333',
    'surface': '0xFFFEFEFE',
    'onSurface': '0xFF333333',
    'primaryContainer': '0xFFF05D4D',
    'onPrimaryContainer': '0xFFFEFEFE',
    'secondaryContainer': '0xFF197BBD',
    'onSecondaryContainer': '0xFFFAFAFA',
    'tertiary': '0xFF5D5D5D',
    'onTertiary': '0xFFFAFAFA',
    'tertiaryContainer': '0xFFFF00FF',
    'onTertiaryContainer': '0xFF00FF00',
    'errorContainer': '0xFFCC00CC',
    'onErrorContainer': '0xFFCCFFCC',
    'surfaceVariant': '0xFFFFFF00',
    'onSurfaceVariant': '0xFF0000FF',
    'outline': '0xFFCCCC00',
    'shadow': '0xFFFF0000',
    'inverseSurface': '0xFF00F0FF',
    'onInverseSurface': '0xFF990000',
    'inversePrimary': '0xFFAA99DD',
    'surfaceTint': '0xFFAADD22',
  };

  static final Map<String, String> theme7 = {
    'schemeName': 'theme7',
    'brightness': 'light',
    'primary': '0xFFFAF3E3',
    'onPrimary': '0xFF333333',
    'secondary': '0xFFEF5253',
    'onSecondary': '0xFFFAF3E3',
    'error': '0xFFEF5253',
    'onError': '0xFFFAFAFA',
    'background': '0xFFFEFEFE',
    'onBackground': '0xFF333333',
    'surface': '0xFFFAF3E3',
    'onSurface': '0xFF333333',
    'primaryContainer': '0xFFF4D474',
    'onPrimaryContainer': '0xFFFAF3E3',
    'secondaryContainer': '0xFFEF5253',
    'onSecondaryContainer': '0xFFFAFAFA',
    'tertiary': '0xFF5D5D5D',
    'onTertiary': '0xFFFAFAFA',
    'tertiaryContainer': '0xFFFF00FF',
    'onTertiaryContainer': '0xFF00FF00',
    'errorContainer': '0xFFCC00CC',
    'onErrorContainer': '0xFFCCFFCC',
    'surfaceVariant': '0xFFFFFF00',
    'onSurfaceVariant': '0xFF0000FF',
    'outline': '0xFFCCCC00',
    'shadow': '0xFFFF0000',
    'inverseSurface': '0xFF00F0FF',
    'onInverseSurface': '0xFF990000',
    'inversePrimary': '0xFFAA99DD',
    'surfaceTint': '0xFFAADD22',
  };

  static final Map<String, String> theme8 = {
    'schemeName': 'theme8',
    'brightness': 'light',
    'primary': '0xFFFFDD8C',
    'onPrimary': '0xFF333333',
    'secondary': '0xFFF4B41A',
    'onSecondary': '0xFFFAFAFA',
    'error': '0xFFEF5253',
    'onError': '0xFFFAFAFA',
    'background': '0xFFFEFEFE',
    'onBackground': '0xFF333333',
    'surface': '0xFFFFDD8C',
    'onSurface': '0xFF333333',
    'primaryContainer': '0xFFF4B41A',
    'onPrimaryContainer': '0xFFFFDD8C',
    'secondaryContainer': '0xFF143D59',
    'onSecondaryContainer': '0xFFFAFAFA',
    'tertiary': '0xFF5D5D5D',
    'onTertiary': '0xFFFAFAFA',
    'tertiaryContainer': '0xFFFF00FF',
    'onTertiaryContainer': '0xFF00FF00',
    'errorContainer': '0xFFCC00CC',
    'onErrorContainer': '0xFFCCFFCC',
    'surfaceVariant': '0xFFFFFF00',
    'onSurfaceVariant': '0xFF0000FF',
    'outline': '0xFFCCCC00',
    'shadow': '0xFFFF0000',
    'inverseSurface': '0xFF00F0FF',
    'onInverseSurface': '0xFF990000',
    'inversePrimary': '0xFFAA99DD',
    'surfaceTint': '0xFFAADD22',
  };

  static final Map<String, String> theme9 = {
    'schemeName': 'theme9',
    'brightness': 'light',
    'primary': '0xFFFFDD8C',
    'onPrimary': '0xFF333333',
    'secondary': '0xFFDD7373',
    'onSecondary': '0xFFFAFAFA',
    'error': '0xFFEF5253',
    'onError': '0xFFFAFAFA',
    'background': '0xFFFEFEFE',
    'onBackground': '0xFF333333',
    'surface': '0xFFFEFEFE',
    'onSurface': '0xFF333333',
    'primaryContainer': '0xFFFEFEFE',
    'onPrimaryContainer': '0xFFFFBC57',
    'secondaryContainer': '0xFFFEFEFE',
    'onSecondaryContainer': '0xFFFAFAFA',
    'tertiary': '0xFF5D5D5D',
    'onTertiary': '0xFFFAFAFA',
    'tertiaryContainer': '0xFFFF00FF',
    'onTertiaryContainer': '0xFF00FF00',
    'errorContainer': '0xFFCC00CC',
    'onErrorContainer': '0xFFCCFFCC',
    'surfaceVariant': '0xFFFFFF00',
    'onSurfaceVariant': '0xFF0000FF',
    'outline': '0xFFCCCC00',
    'shadow': '0xFFFF0000',
    'inverseSurface': '0xFF00F0FF',
    'onInverseSurface': '0xFF990000',
    'inversePrimary': '0xFFAA99DD',
    'surfaceTint': '0xFFAADD22',
  };

  static final Map<String, String> theme10 = {
    'schemeName': 'theme10',
    'brightness': 'light',
    'primary': '0xFFFFFEE6',
    'onPrimary': '0xFF333333',
    'secondary': '0xFFFFBC59',
    'onSecondary': '0xFFFFFEE6',
    'error': '0xFFEF5253',
    'onError': '0xFFFAFAFA',
    'background': '0xFFFEFEFE',
    'onBackground': '0xFF333333',
    'surface': '0xFFFEFEFE',
    'onSurface': '0xFF333333',
    'primaryContainer': '0xFFFEFEFE',
    'onPrimaryContainer': '0xFF53A644',
    'secondaryContainer': '0xFFFEFEFE',
    'onSecondaryContainer': '0xFFFAFAFA',
    'tertiary': '0xFF5D5D5D',
    'onTertiary': '0xFFFAFAFA',
    'tertiaryContainer': '0xFFFF00FF',
    'onTertiaryContainer': '0xFF00FF00',
    'errorContainer': '0xFFCC00CC',
    'onErrorContainer': '0xFFCCFFCC',
    'surfaceVariant': '0xFFFFFF00',
    'onSurfaceVariant': '0xFF0000FF',
    'outline': '0xFFCCCC00',
    'shadow': '0xFFFF0000',
    'inverseSurface': '0xFF00F0FF',
    'onInverseSurface': '0xFF990000',
    'inversePrimary': '0xFFAA99DD',
    'surfaceTint': '0xFFAADD22',
  };

  static final Map<String, String> theme11 = {
    'schemeName': 'theme11',
    'brightness': 'dark',
    'primary': '0xFF354F6F',
    'onPrimary': '0xFFFAFAFA',
    'secondary': '0xFFF75C2F',
    'onSecondary': '0xFFFAFAFA',
    'error': '0xFFEF5253',
    'onError': '0xFFFAFAFA',
    'background': '0xFF041529',
    'onBackground': '0xFFFAFAFA',
    'surface': '0xFF041529',
    'onSurface': '0xFFFAFAFA',
    'primaryContainer': '0xFFF75C2F',
    'onPrimaryContainer': '0xFFFAFAFA',
    'secondaryContainer': '0xFF041529',
    'onSecondaryContainer': '0xFFFAFAFA',
    'tertiary': '0xFFA2A2A2',
    'onTertiary': '0xFFFAFAFA',
    'tertiaryContainer': '0xFFFF00FF',
    'onTertiaryContainer': '0xFF00FF00',
    'errorContainer': '0xFFCC00CC',
    'onErrorContainer': '0xFFCCFFCC',
    'surfaceVariant': '0xFFFFFF00',
    'onSurfaceVariant': '0xFF0000FF',
    'outline': '0xFFCCCC00',
    'shadow': '0xFFFF0000',
    'inverseSurface': '0xFF00F0FF',
    'onInverseSurface': '0xFF990000',
    'inversePrimary': '0xFFAA99DD',
    'surfaceTint': '0xFFAADD22',
  };
}

List<Color> theme1 = [
  const Color(0xFFF75C2F),
  const Color(0xFFFFC700),
  const Color(0xFFFFF5D2),
  const Color(0xFFFFFEFC),
];

List<Color> theme2 = [
  const Color(0xFF0D5661),
  const Color(0xFFFFB11B),
  const Color(0xFFFFCF71),
  const Color(0xFFFFF7E8),
  const Color(0xFFFFFEFC),
];

List<Color> theme3 = [
  const Color(0xFF464EF2),
  const Color(0xFFF18D5F),
  const Color(0xFFFDF0EA),
  const Color(0xFFF9F9F9),
];

List<Color> theme4 = [
  const Color(0xFF255F85),
  const Color(0xFFE98A15),
  const Color(0xFFFFFFEA),
  const Color(0xFFF9F9F9),
];

List<Color> theme5 = [
  const Color(0xFFF4AF1B),
  const Color(0xFFFFD55A),
  const Color(0xFF66D47E),
  const Color(0xFFFEFEFE),
  const Color(0xFF333333),
];

List<Color> theme6 = [
  const Color(0xFF197BBD),
  const Color(0xFFF05D4D),
  const Color(0xFF88AB75),
  const Color(0xFFFEFEFE),
];

List<Color> theme7 = [
  const Color(0xFFEF5253),
  const Color(0xFFF4D474),
  const Color(0xFFFAF3E3),
  const Color(0xFFFEFEFE),
];

List<Color> theme8 = [
  const Color(0xFF143D59),
  const Color(0xFFF4B41A),
  const Color(0xFFFFDD8C),
  const Color(0xFFFEFEFE),
];

List<Color> theme9 = [
  const Color(0xFFFFBC57),
  const Color(0xFFFFDD8C),
  const Color(0xFFDD7373),
  const Color(0xFFFEFEFE),
];

List<Color> theme10 = [
  const Color(0xFF53A644),
  const Color(0xFFFFBC59),
  const Color(0xFFFFFEE6),
  const Color(0xFFFEFEFE),
];

List<Color> theme11 = [
  const Color(0xFF041529),
  const Color(0xFF354F6F),
  const Color(0xFFF75C2F),
  const Color(0xFFFAFAFA),
];
